### ISSUE TITLE
[Suggestion] Use javascript UI in Colab

### ISSUE THREAD

**Issue by gpt2ent** [ADGEfficiency/creative-writing-with-gpt2#5]
I have a Colab Notebook repo that proves it is possible to communicate to GPT-2 via HTML+JS output: [repo](https://github.com/gpt2ent/gpt2colab-js), [notebook](https://colab.research.google.com/github/gpt2ent/gpt2colab-js/blob/master/GPT2_with_Javascript_interface_POC.ipynb)
![This is how it looks](https://raw.githubusercontent.com/gpt2ent/gpt2colab-js/master/gpt2js.png)

I actually came to use it a lot in my experiments. Above all, the snippet is resilient to runtime disconnects.

**Comment by ADGEfficiency** [comment]
Hello @gpt2ent - thank you for the PR, sorry it took me so long.  Looks interesting!

In `GPT2_with_Javascript_interface_POC.ipynb`, you seem to be connecting to [gpt-2-simple](https://github.com/gpt2ent/gpt-2-simple) which is based on the Open AI models.  

I'm using a thin wrapper around HuggingFace - would I need to write an interface to my HuggingFace wrapper to use your work?
